### PR TITLE
Adds a delete method to the client module.

### PR DESCRIPTION
**Pull request by mszymulanski**
This change gives the driver to use Couch's `delete` request method

### CODE REVIEW

**Review by scull7 — APPROVED** [review]

**Comment by jxbadam** [comment]
CI is not happy (failing test)... Unhandled Rejection: test/add-index.spec.js
  HTTPError
    stream.catch.then.data (/home/travis/build/influentialpublishers/got-couch/node_modules/got/index.js:119:13)
    process._tickCallback (internal/process/next_tick.js:103:7)
    
Unhandled Rejection: test/spec.js
  HTTPError
    stream.catch.then.data (/home/travis/build/influentialpublishers/got-couch/node_modules/got/index.js:119:13)
    process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by mszymulanski** [comment]
@scull7 @jxbadam Re-review please.

**Review by jxbadam — APPROVED** [review]
:shipit: :fire:

**Review by scull7 — APPROVED** [review]
:shipit:

**Pull request merged**
